### PR TITLE
added desccription for #12

### PR DESCRIPTION
**Pull request by JeroenDeDauw**
added user friendly description for #12

### CODE REVIEW

**Comment by kghbln** [comment]
@JeroenDeDauw @oetterer I just updated sandbox.s-mw.o (Chameleson is `@dev` and pulls in everything it needs) and Chameleon does not load properly. The browser console is full of errors. Not sure if the 4.1 release is to blame or if the issue was there before. Still using SCSS but disabling it does not change the issue. So I enabled it again.

**Comment by oetterer** [comment]
@kghbln tested with
* MediaWiki | 1.34.0 (29977eb)
* PHP | 7.3.11
* Chameleon | 2.2.0 (@dev)
* Bootstrap | 4.1 (dc0e3fd)

works fine, no problems.

**Comment by kghbln** [comment]
@oetterer Could you have a look at sandbox and switch to Chameleon to get an idea of what I am seeing?

**Comment by oetterer** [comment]
I got it down to the request for https://sandbox.semantic-mediawiki.org/w/load.php?debug=true&lang=en&modules=zzz.ext.bootstrap.styles&only=styles&skin=chameleon returning
```css
/* SCSS compile error: expecting color, function received: /var/www/html/sbxsmw/w/skins/chameleon/resources/styles/_variables.scss on line 36*/
```
Same error as in #11, but I don't think, they have the same origin.

**Comment by JeroenDeDauw** [comment]
Why do you think these errors have a different source? It's the exact same error with the exact same line.

**Comment by JeroenDeDauw** [comment]
@kghbln so chameleon worked fine before the update but fails after?

**Comment by oetterer** [comment]
@JeroenDeDauw because it was fixed and merged in #12

**Comment by s7eph4n** [comment]
This issue looks similar: https://github.com/scssphp/scssphp/issues/54
The solution was to make sure that the `theme-color()` function is available

**Comment by JeroenDeDauw** [comment]
The `theme-color` function is defined in the Bootstrap extension in `resoucrs/bootstrap/scss/_functions.scss`.

Lets isolate which change broke things. @kghbln can you undo this change on sandbox? https://github.com/ProfessionalWiki/Bootstrap/pull/12 (you can manually edit the file). If that does not fix the issue, then the remaining change made is the switch to new version of scssphp.

**Comment by oetterer** [comment]
@kghbln are you currently dabbling with the sandbox's extensions? if not: bootstrap is somehow still at 4.0 where it should be at least 4.1 if not @dev

**Comment by oetterer** [comment]
@kghbln I don't know if you are already reverting, but currently Bootstrap is at 4.0 where it should be 4.1. if this is not of your doing, it could explain the problem.

**Comment by kghbln** [comment]
@oetterer Sorry for responding late. Was in a 3 hour telco.

I do not longer have a call to Bootstrap in composer.local.json thus I believe that Chameleon at dev pulls in Bootstrap 4.0 instead of 4.1. I think Iremoved the call since Composer was unable to install due to unsolvable dependencies.

**Comment by kghbln** [comment]
If I add `@dev` I get 0c09a63722beef31ef9c03ec273b29d1ef8ce584 and if I add `~4.1` I get:

```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - mediawiki/bootstrap 4.1.0 requires mediawiki/scss ~2.0 -> satisfiable by mediawiki/scss[2.0.0, 2.x-dev] but these conflict with your requirements or minimum-stability.
    - Removal request for mediawiki/bootstrap == 4.9999999.9999999.9999999-dev
    - Installation request for mediawiki/bootstrap ~4.1 -> satisfiable by mediawiki/bootstrap[4.1.0, 4.x-dev].
```
Now I know why I removed the call to Bootstrap. "composer.json" must still be tweaked here I guess.

**Comment by kghbln** [comment]
The issue was connected to my comment here: https://github.com/ProfessionalWiki/Bootstrap/pull/21#issuecomment-617656664

Basically I wanted to know if the CCCP extension is still needed, which it is not. After removing "mediawiki/cccp" from the "compser.local.json" and no longer invoking it in "LocalSettings.php" everything is flauschig again, since Chameleon moves in the latest version of Bootstrap and the new "mediawiki./cccp" library and moves out the "mediawiki/cccp" extension.

To cut it short: Once we release a new version of Chameleon we need to make sure to instruct sysadmins to avoid the pain we just saw here.

**Pull request merged**
